adlist.o: adlist.c adlist.h zmalloc.h
ae.o: ae.c ae.h monotonic.h fmacros.h anet.h zmalloc.h config.h \
  ae_kqueue.c
ae_kqueue.o: ae_kqueue.c
ae_select.o: ae_select.c
anet.o: anet.c fmacros.h anet.h
crc64.o: crc64.c crc64.h crcspeed.h
crcspeed.o: crcspeed.c crcspeed.h
dict.o: dict.c fmacros.h dict.h mt19937-64.h zmalloc.h redisassert.h \
  config.h
endianconv.o: endianconv.c
geohash.o: geohash.c geohash.h
geohash_helper.o: geohash_helper.c fmacros.h geohash_helper.h geohash.h \
  debugmacro.h
intset.o: intset.c intset.h zmalloc.h endianconv.h config.h redisassert.h
listpack.o: listpack.c listpack.h listpack_malloc.h zmalloc.h \
  redisassert.h config.h
localtime.o: localtime.c
lzf_c.o: lzf_c.c lzfP.h
lzf_d.o: lzf_d.c lzfP.h
memtest.o: memtest.c config.h
monotonic.o: monotonic.c monotonic.h fmacros.h
mt19937-64.o: mt19937-64.c mt19937-64.h
pqsort.o: pqsort.c
quicklist.o: quicklist.c quicklist.h zmalloc.h config.h ziplist.h util.h \
  sds.h lzf.h redisassert.h
rand.o: rand.c
rax.o: rax.c rax.h rax_malloc.h zmalloc.h
release.o: release.c release.h version.h crc64.h
sds.o: sds.c sds.h sdsalloc.h zmalloc.h
setcpuaffinity.o: setcpuaffinity.c config.h
setproctitle.o: setproctitle.c
sha1.o: sha1.c solarisfixes.h sha1.h config.h
sha256.o: sha256.c sha256.h
siphash.o: siphash.c
util.o: util.c fmacros.h util.h sds.h sha256.h
ziplist.o: ziplist.c zmalloc.h util.h sds.h ziplist.h config.h \
  endianconv.h redisassert.h
zipmap.o: zipmap.c zmalloc.h endianconv.h config.h
zmalloc.o: zmalloc.c config.h zmalloc.h atomicvar.h
